/**
 * Creation/modification date: 01/06/2026
 * Path: src/services/pdf/labels.ts
 * Description: Multi-language labels for PDF documents.
 *              Pure data, no logic.
 */

import type { Lang } from "./types";

export const LABELS: Record<Lang, Record<string, string>> = {
  ca: {
    headerSubtitle: "Informe d'Ordre de Treball",
    quoteDocTitle: "Pressupost",
    quoteNum: "NUM.",
    client: "CLIENT",
    workOrderDetails: "DETALLS DE L'ORDRE",
    description: "DESCRIPCIÓ",
    materials: "MATERIALS",
    attachments: "IMATGES ADJUNTES",
    signature: "SIGNATURA DIGITAL",
    company: "EMPRESA",
    total: "TOTAL",
    generated: "Generat",
    reportFooterSuffix: "Informe generat automaticament",
    name: "Nom",
    phone: "Telèfon",
    email: "Correu",
    address: "Adreça",
    status: "Estat",
    priority: "Prioritat",
    category: "Categoria",
    scheduled: "Programada",
    started: "Iniciada",
    completed: "Completada",
    qty: "Qt.",
    unitPrice: "Preu Unit.",
    lineTotal: "Import",
    before: "Abans",
    after: "Despres",
    signedBy: "Signada per",
    none: "—",
    from: "De:",
    to: "Per a:",
    issueDate: "Data emissio:",
    validity: "Validesa:",
    term: "Termini:",
    days: "dies",
    workDescription: "Descripcio del treball",
    ref: "Ref.",
    itemConcept: "Descripcio del Concepte",
    itemUnits: "Unitats",
    itemUnitPriceCol: "Preu Unitari",
    itemTotalCol: "Total",
    conditionsTitle: "Condicions generals i forma de pagament",
    signatureTitle: "Acceptacio del Pressupost",
    signatureCaption:
      "Per aprovar i formalitzar la comanda, si us plau, signeu i retorneu aquest document.",
    signatureLine: "Signatura del client i data",
    signatureThanks: "Gracies per la seva confiança.",
    signedOn: "Signat el",
    acceptedBy: "Acceptat per",
    acceptanceConfirmed: "Acceptacio confirmada",
  },
  es: {
    headerSubtitle: "Informe de Orden de Trabajo",
    quoteDocTitle: "Presupuesto",
    quoteNum: "NUM.",
    client: "CLIENTE",
    workOrderDetails: "DETALLES DE LA ORDEN",
    description: "DESCRIPCIÓN",
    materials: "MATERIALES",
    attachments: "IMÁGENES ADJUNTAS",
    signature: "FIRMA DIGITAL",
    company: "EMPRESA",
    total: "TOTAL",
    generated: "Generado",
    reportFooterSuffix: "Informe generado automaticamente",
    name: "Nombre",
    phone: "Teléfono",
    email: "Correo",
    address: "Dirección",
    status: "Estado",
    priority: "Prioridad",
    category: "Categoría",
    scheduled: "Programada",
    started: "Iniciada",
    completed: "Completada",
    qty: "Cant.",
    unitPrice: "Precio Unit.",
    lineTotal: "Importe",
    before: "Antes",
    after: "Despues",
    signedBy: "Firmada por",
    none: "—",
    from: "De:",
    to: "Para:",
    issueDate: "Fecha emision:",
    validity: "Validez:",
    term: "Plazo:",
    days: "dias",
    workDescription: "Descripcion del trabajo",
    ref: "Ref.",
    itemConcept: "Descripcion del Concepto",
    itemUnits: "Unidades",
    itemUnitPriceCol: "Precio Unitario",
    itemTotalCol: "Total",
    conditionsTitle: "Condiciones generales y forma de pago",
    signatureTitle: "Aceptacion del Presupuesto",
    signatureCaption:
      "Para aprobar y formalizar el pedido, por favor firme y devuelva este documento.",
    signatureLine: "Firma del cliente y fecha",
    signatureThanks: "Gracias por su confianza.",
    signedOn: "Firmado el",
    acceptedBy: "Aceptado por",
    acceptanceConfirmed: "Aceptacion confirmada",
  },
  en: {
    headerSubtitle: "Work Order Report",
    quoteDocTitle: "Quote",
    quoteNum: "NO.",
    client: "CLIENT",
    workOrderDetails: "WORK ORDER DETAILS",
    description: "DESCRIPTION",
    materials: "MATERIALS",
    attachments: "ATTACHED IMAGES",
    signature: "DIGITAL SIGNATURE",
    company: "COMPANY",
    total: "TOTAL",
    generated: "Generated",
    reportFooterSuffix: "Automatically generated report",
    name: "Name",
    phone: "Phone",
    email: "Email",
    address: "Address",
    status: "Status",
    priority: "Priority",
    category: "Category",
    scheduled: "Scheduled",
    started: "Started",
    completed: "Completed",
    qty: "Qty",
    unitPrice: "Unit Price",
    lineTotal: "Line Total",
    before: "Before",
    after: "After",
    signedBy: "Signed by",
    none: "—",
    from: "From:",
    to: "To:",
    issueDate: "Issue date:",
    validity: "Validity:",
    term: "Term:",
    days: "days",
    workDescription: "Work description",
    ref: "Ref.",
    itemConcept: "Item Description",
    itemUnits: "Units",
    itemUnitPriceCol: "Unit Price",
    itemTotalCol: "Total",
    conditionsTitle: "General conditions and payment terms",
    signatureTitle: "Quote Acceptance",
    signatureCaption: "To approve and formalize the order, please sign and return this document.",
    signatureLine: "Client signature and date",
    signatureThanks: "Thank you for your trust.",
    signedOn: "Signed on",
    acceptedBy: "Accepted by",
    acceptanceConfirmed: "Acceptance confirmed",
  },
};
